backend:
  # name: git-gateway
  name: github
  repo: alisson-suzigan/store-cms
  branch: master # Branch to update (optional; defaults to master)

site_url: https://storecms.netlify.app
display_url: https://storecms.netlify.app
# logo_url: https://your-site.com/images/logo.svg
locale: 'pt-br'
# show_preview_links: true
# slug:
#   encoding: "ascii"
#   clean_accents: true
#   sanitize_replacement: "-"

# Enabling Editorial Workflow: interface for drafting, reviewing, and approving posts
# publish_mode: editorial_workflow

# Media files will be stored in the repo under images/uploads
media_folder: 'static/images/uploads' # Media files will be stored in the repo under static/images/uploads
public_folder: '/images/uploads' # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: 'product' # Used in routes, e.g., /admin/collections/product
    label: 'Produto' # Used in the UI
    folder: 'static/content/product' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'product' }
      - { label: 'Nome', name: 'title', widget: 'string' }
      - { label: 'Descrição', name: 'description', widget: 'markdown' }
      - { label: 'Valor', name: 'value', widget: 'number', valueType: 'float' }
      - { label: 'Disponível', name: 'available', widget: 'boolean', required: false, default: true }
      - { label: 'Fotos', name: 'gallery', widget: 'list', field: { label: Imagem, name: image, widget: image } }

      - label: 'Categorias'
        name: 'categories'
        widget: 'list'
        required: true
        fields:
          - label: 'Categoria'
            name: 'category'
            widget: 'relation'
            collection: 'category'
            searchFields: ['title']
            valueField: 'title'

  - name: 'category'
    label: 'Categoria'
    folder: 'static/content/category'
    slug: '{{slug}}'
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'category' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Icone', name: 'icon', widget: 'string', required: false }
